export const PEER_REGISTER = "PEER_REGISTER";
export const PEER_CHANGE_NAME = "PEER_CHANGE_NAME";
export const PEER_CHANGE_CONN_NAME = "PEER_CHANGE_CONN_NAME";
export const PEER_CONNECTED = "PEER_CONNECTED";
export const PEER_CHANGE_MESSAGE = "PEER_CHANGE_MESSAGE";
export const PEER_SEND_MESSAGE = "PEER_SEND_MESSAGE";
export const PEER_RECIEVE_MESSAGE = "PEER_RECIEVE_MESSAGE";